In [ ]:
import tensorflow as tf

### 2.5.1 A Simple Fuction

In [ ]:
x = tf.Variable(tf.range(4, dtype = tf.float32))
x

In [ ]:
with tf.GradientTape() as t:
    y = 2 * tf.tensordot(x, x, axes= 1)
y

In [ ]:
x_grad = t.gradient(y,x)
x_grad

In [ ]:
x_grad == 4 * x

In [ ]:
with tf.GradientTape() as t:
    y = tf.reduce_sum(x)
t.gradient(y,x)

### 2.5.2 Backward for Non-Scalar Variables

In [ ]:
with tf.GradientTape() as t:
    y = x * x
t.gradient(y,x)

### 2.5.3 Detaching Computation

In [14]:
# Set persistent = True to preserve the compute graph.
# This lets us run t.gradient more than once

with tf.GradientTape(persistent=True) as t:
    y = x * x
    u = tf.stop_gradient(y)
    z = u * x
    
x_grad = t.gradient(z,x)
x_grad == u, x_grad

(<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True,  True,  True,  True])>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 4., 9.], dtype=float32)>)

In [15]:
t.gradient(y, x) == 2 * x

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True,  True,  True,  True])>

In [ ]:
with tf.GradientTape() as t:
    z = x * x * x
x_grad2 = t.gradient(z,x)
x_grad2 == u, x_grad2

### 2.5.4 Gradients and Python control Flow

In [16]:
def f(a):
    b = a * 2
    while tf.norm(b) < 1000:
        b  = b * 2
    if tf.reduce_sum(b) > 0:
        c = b
    else:
        c = 100 * b
    return c

In [17]:
a = tf.Variable(tf.random.normal(shape=()))
with tf.GradientTape() as t:
    d = f(a)
d_grad = t.gradient(d,a)
d_grad

<tf.Tensor: shape=(), dtype=float32, numpy=65536.0>

In [19]:
d_grad == d / a

<tf.Tensor: shape=(), dtype=bool, numpy=True>